name: purchases_dart_stripe
description: "A pure Dart implementation of purchases_flutter(aka RevenueCat)."
version: 1.0.0
homepage:
homepage: https://navideck.com
repository: https://github.com/Navideck/purchases_dart_stripe
issue_tracker: https://github.com/Navideck/purchases_dart_stripe/issues
funding:
  - https://github.com/sponsors/Navideck

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  purchases_flutter: ^6.24.0
  purchases_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0