import 'package:purchases_dart/src/helper/attributes_manager.dart';
import 'package:purchases_dart/src/helper/cache_manager.dart';
import 'package:purchases_dart/src/helper/identity_manager.dart';
import 'package:purchases_dart/src/helper/logger.dart';
import 'package:purchases_dart/src/model/purchases_header.dart';
import 'package:purchases_dart/src/model/raw_customer.dart';
import 'package:purchases_dart/src/model/subscribe_attributes_key.dart';
import 'package:purchases_dart/src/networking/purchases_backend.dart';
import 'package:purchases_dart/src/parser/customer_parser.dart';
import 'package:purchases_dart/src/purchases_dart_configuration.dart';
import 'package:purchases_flutter/purchases_flutter.dart';

/// Entry point for PurchasesDart.
class PurchasesDart {
  static PurchasesBackend? _backend;
  static final CustomerParser _customerParser = CustomerParser();
  static late CacheManager _cacheManager;
  static late AttributeManager _attributeManager;
  static late IdentityManager _identityManager;

  /// Gets the current appUserID.
  static String? get appUserId => _identityManager.currentAppUserId;

  /// Sets up Purchases with your API key and an app user id.
  ///
  /// [PurchasesDartConfiguration] Object containing configuration parameters
  /// Make sure to call this method before calling any other methods, and only call it once.
  static Future<void> configure(
    PurchasesDartConfiguration configuration,
  ) async {
    if (_backend != null) throw Exception("PurchasesDart already configured");
    _cacheManager = await CacheManager.instance;
    _backend = PurchasesBackend(
      apiKey: configuration.webBillingApiKey,
    );
    _identityManager = IdentityManager(_cacheManager, _backend!);
    _attributeManager = AttributeManager(_backend!);
    _identityManager.configure(configuration.appUserId);
  }

  /// Configures log level
  /// Used to set the log level. Useful for debugging issues with the lovely team @RevenueCat.
  /// The default is [LogLevel.info] in release builds and [LogLevel.debug] in debug builds.
  static void setLogLevel(LogLevel level) => Logger.logLevel = level;

  /// Set a custom log handler for redirecting logs to your own logging system.
  /// If you wish to receive Debug level messages, see [setLogLevel].
  ///
  /// [logHandler] It will get called for each log event.
  /// Use this function to redirect the log to your own logging system
  static void setLogHandler(LogHandler logHandler) =>
      Logger.logHandler = logHandler;

  /// Gets current customer info. If the customer does not exist it will create one using the `appUserId` provided during configuration.
  static Future<CustomerInfo?> getCustomerInfo({
    PurchasesHeader? headers,
  }) async {
    String userId = _validateConfigAndGetUserId();
    return await _backend?.getCustomerInfo(
      userId,
      headers: headers,
    );
  }

  /// Fetch the configured offerings for this users. Offerings allows you to
  /// configure your products via RevenueCat and greatly simplifies
  /// management. See [the guide](https://docs.revenuecat.com/offerings) for
  /// more info.
  static Future<Offerings?> getOfferings({
    PurchasesHeader? headers,
  }) async {
    String userId = _validateConfigAndGetUserId();
    return await _backend?.getOfferings(
      userId,
      headers: headers,
    );
  }

  /// This function will logIn the current user with an appUserID.
  /// Typically this would be used after logging in a user to identify them without
  /// calling configure
  ///
  /// Returns a [LogInResult] object, or throws a Exception if there
  /// was a problem restoring transactions. LogInResult holds a [CustomerInfo] object
  /// and a bool that can be used to know if a user has just been created for the first time.
  ///
  /// [newAppUserId] The appUserID that should be linked to the currently user
  @Deprecated(
      'Login method using undocumented APIs which might change or stop working, set appUserId in configure instead, or to change id of current user, use updateAppUserId method.')
  static Future<LogInResult> login(String newAppUserId) async {
    _validateConfigAndGetUserId(newAppUserId);
    return _identityManager.logIn(newAppUserId);
  }

  /// Logs out the  Purchases client, clearing the saved appUserID. This will
  /// generate a random user id and save it in the cache.
  static Future<void> logout() => _identityManager.logOut();

  /// If the [appUserId] has been generated by RevenueCat
  static Future<bool> get isAnonymous async =>
      _identityManager.currentUserIsAnonymous();

  /// Update app user id, this will change the current app user id locally
  /// This will not change the app user id in the RevenueCat backend
  static Future<void> updateAppUserId(String appUserId) async {
    _validateConfigAndGetUserId(appUserId);
    await _identityManager.updateAppUserId(appUserId);
  }

  /// Makes a purchase. Might throw [Exception]
  /// Check if [PurchasesErrorHelper.getErrorCode] is
  /// [PurchasesErrorCode.purchaseCancelledError] to check if the user cancelled
  /// the purchase.
  ///
  /// [packageToPurchase] The Package you wish to purchase
  // static Future<void> purchasePackage(Package packageToPurchase) async {
  //   _validateConfigAndGetUserId();
  //   throw UnimplementedError(
  //     "This method is not implemented, please use getWebBillingUrl to get the web billing url and redirect the user to it",
  //   );
  // }

  /// Get the web billing url for a package
  ///
  /// [package] The Package you wish to get the web billing url for
  /// [email] The email of the user you wish to purchase the package for
  static Future<Uri?> getWebBillingUrl(
    Package package, {
    String? email,
  }) async {
    String userId = _validateConfigAndGetUserId();
    var urls = await _backend?.getWebBillingUrl(userId, package);
    Uri? resultUrl = urls?.production;
    if (_backend?.isSandbox == true && urls?.sandbox != null) {
      resultUrl = urls?.sandbox;
    }
    if (resultUrl != null) {
      resultUrl = resultUrl.replace(queryParameters: {
        ...resultUrl.queryParameters,
        if (email != null) "email": email,
      });
    }
    return resultUrl;
  }

  /// Subscriber attribute associated with the Firebase Instance Id for the user
  /// Required for the RevenueCat Firebase integration
  ///
  /// [firebaseAppInstanceId] Empty String or null will delete the subscriber attribute.
  /// This wont sync automatically when userId changes..
  static Future<void> setFirebaseAppInstanceId(
    String? firebaseAppInstanceId,
  ) async {
    String userId = _validateConfigAndGetUserId();
    await _attributeManager.setAttributionID(
      ReservedSubscriberAttribute.FIREBASE_APP_INSTANCE_ID,
      firebaseAppInstanceId,
      userId,
    );
  }

  /// Subscriber attributes are useful for storing additional, structured information on a user.
  /// Since attributes are writable using a public key they should not be used for
  /// managing secure or sensitive information such as subscription status, coins, etc.
  ///
  /// Key names starting with "$" are reserved names used by RevenueCat. For a full list of key
  /// restrictions refer to our guide: https://docs.revenuecat.com/docs/subscriber-attributes
  ///
  /// [attributes] Map of attributes by key. Set the value as an empty string to delete an attribute.
  /// This wont sync automatically when userId changes..
  Future<void> setAttributionID(Map<String, String> attributes) async {
    String userId = _validateConfigAndGetUserId();
    await _attributeManager.setAttributes(
      userId,
      attributes,
    );
  }

  static Future<WebPurchaseRedemption?> parseAsWebPurchaseRedemption(
    String urlString,
  ) async {
    Uri uri = Uri.parse(urlString);
    const redeemWebPurchaseHost = "redeem_web_purchase";
    if (uri.host == redeemWebPurchaseHost) {
      var redemptionToken = uri.queryParameters["redemption_token"];
      if (redemptionToken != null) {
        return WebPurchaseRedemption(redemptionToken);
      }
    }
    return null;
  }

  /// Creates a [CustomerInfo] object from a json object
  static CustomerInfo? createCustomer(Map<String, dynamic> json) =>
      _customerParser.createCustomer(RawCustomer.fromJson(json));

  /// Validates the configuration, throws an exception if the configuration is not valid
  static String _validateConfigAndGetUserId([String? userId]) {
    if (_backend == null) {
      throw Exception(
        "PurchasesDart.configure() must be called before calling any other methods",
      );
    }
    String? validUserId = userId ?? appUserId;
    if (validUserId == null) {
      throw Exception(
        "Failed to get userId, please set in configure method or pass userId to the method",
      );
    }
    return validUserId;
  }
}
